import type { Metadata } from "next";
import "./globals.css";
import Footer from "./componets/footer";
import NavBar from "./componets/Navebar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
  
      <body>
     
      <NavBar/>
        {children} 

        <Footer/>
      </body>
    </html>
  );
}